name: 🌩️ Auto Deploy to Cyclic

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Cyclic
        env:
          CYCLIC_API_KEY: ${{ secrets.CYCLIC_API_KEY }}
        run: |
          curl -X POST https://api.cyclic.sh/deploy \
          -H "Authorization: Bearer $CYCLIC_API_KEY"
